### ISSUE TITLE
Love the site, so I made a bit.ly for it!

### ISSUE THREAD

**Issue by muttoni** [MinhasKamal/DownGit#10]
Users can now use: **[bit.ly/downgit](https://bit.ly/downgit)**

(consider adding to readme as the original url is hard to remember)

Keep up the good work!

**Comment by MinhasKamal** [comment]
Thank you Andrea Muttoni for your suggestion. 

The minified url- [bit.ly/downgit](bit.ly/downgit) will certainly be easy to remember. The direct download link does not work though- 

[bit.ly/downgit?url=https://github.com/s-panferov/awesome-typescript-loader/tree/master/src](bit.ly/downgit?url=https://github.com/s-panferov/awesome-typescript-loader/tree/master/src)

It would have been even better if it did.

**Comment by muttoni** [comment]
Bit.ly is just a URL shortener and doesn't pass on parameters, most likely due to this SO answer here: https://stackoverflow.com/a/2572814

the point of the bitly was to have a quick way of telling people where to find this tool and they can then use the tool as normal (pasting the directory and clicking download)
