### ISSUE TITLE
Should not alter 'file modification date'

### ISSUE THREAD

**Issue by guidezpl** [MinhasKamal/DownGit#13]
I was having issues with my file backup system and found the source of the error. It appears DownGit changes the file modification date, and for me, set it to a few hours in the future.

See an example below, first I downloaded a subset of a repo with DownGit and unzipped/
Then I downloaded the entire repo and looked at the same file, with it's modification date unchanged.

![screen shot 2017-12-27 at 18 39 31](https://user-images.githubusercontent.com/6655696/34396143-4f8078a8-eb35-11e7-87b6-d55a8a7fb7e7.png)

**Comment by MinhasKamal** [comment]
I am not sure, if it is possible to preserve the actual file-modification-date from Github API.
