### ISSUE TITLE
files inside zip renamed?

### ISSUE THREAD

**Issue by rgetz** [MinhasKamal/DownGit#15]
When I tried to use downgit with:

https://github.com/analogdevicesinc/arduino/tree/master/Arduino%20Uno%20R3/examples/CN0216_example

I get the url:

https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/analogdevicesinc/arduino/tree/master/Arduino%20Uno%20R3/examples/CN0216_example

which gives me a zip file, which includes the three files included in the git directory that I'm pointing to, but the names have all changed.

Files:
- AD7791.cpp
- AD7791.h
- CN0216_example.ino

get changed into:
- 91.cpp
- 91.h
- 16_example.ino

**Comment by MinhasKamal** [comment]
@rgetz Thank you a lot Robin Getz for your detailed description.

Facing the same issue from my side. I will look inside the problem and let you know.

**Comment by MinhasKamal** [comment]
@rgetz Please check if everything is alright.

**Comment by rgetz** [comment]
Thanks - now works for me.
