### ISSUE TITLE
website always go down after downloading big repo

### ISSUE THREAD

**Issue by heindrix** [MinhasKamal/DownGit#24]
for example, after i download :
https://github.com/Mi5Devs/proprietary_vendor_xiaomi/tree/lineage-16.0/msm8996-common

and then i want to download :
https://github.com/TheMuppets/proprietary_vendor_xiaomi/tree/lineage-16.0/msm8996-common
on this part, the downgit website will down.

**Comment by Hebgbs** [comment]
Yeah that's happened to me today. I was only _testing_ my DownGit URLs for validity.
