### ISSUE TITLE
The xxx.zip need password

### ISSUE THREAD

**Issue by shz2050** [MinhasKamal/DownGit#3]
Hi, I downloaded the file used the DownGit. But the xxx.zip file need password.
What is the password for unzip?
Thanks

**Comment by MinhasKamal** [comment]
That should never be the case! There is no password required for unzip.
Could you please send me the link to the github directory?

**Comment by shz2050** [comment]
Try this
https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/samdmarshall/OSXPrivateSDK/blob/master/PrivateSDK10.10.sparse.sdk/usr/local/include/os/lock_private.h

When I use betterzip to unzip, It hint "Enter password".

**Comment by MinhasKamal** [comment]
That is not a directory! you gave a link to file- https://github.com/samdmarshall/OSXPrivateSDK/blob/master/PrivateSDK10.10.sparse.sdk/usr/local/include/os/lock_private.h

**Comment by MinhasKamal** [comment]
Do you want file- 'lock_private.h', or the 'os' directory.

**Comment by shz2050** [comment]
Thanks,
It's my mistake. The DownGit only support download directory. I was download a file.

**Comment by MinhasKamal** [comment]
Thank you. I am closing the issue then.

**Comment by MinhasKamal** [comment]
DownGit now can also download file from GitHub.
