### ISSUE TITLE
Blocked in Chrome as "contains harmful programs"

### ISSUE THREAD

**Issue by schuderer** [MinhasKamal/DownGit#31]
First of all, thanks a lot for this useful tool!

Opening a DownGit link triggers a warning in chrome, e.g. https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2Fhello%2Ftest

![image](https://user-images.githubusercontent.com/4430527/75891521-2d51d400-5e30-11ea-909d-fe0214451f31.png)

This happens (in Chrome) for all links I try to open in DownGit.

I am unsure why this is triggered, but sort of get it, as a shortened DownGit link could theoretically be misued to get someone who clicks on it to download (not execute) almost anything from GitHub (but then again, so could GitHubs own "download repo as zip" link, so is it really as bad?...).

I could not find out why this is the case specifically (i.e. what those cases were that Chrome claims were abusing the site to have people harmful things).

**Comment by easyw** [comment]
The same for firefox

**Comment by MinhasKamal** [comment]
I am having the same issue. Seems, someone may have used DownGit in distributing malwares :(

**Comment by justinmassiot** [comment]
Same issue for me. Does someone have an alternative?

**Comment by schuderer** [comment]
My solution was to make zipping the stuff-to-download a part of the build process and to distribute the resulting file with the docs (see referenced PR above your comment). That way, every release has its own examples, which is even somewhat cleaner than before. Not a solution that will fit many use cases, I admit.

**Comment by justinmassiot** [comment]
Not mine at least, but thank you for your idea.

**Comment by MinhasKamal** [comment]
My suggestion is: Fork DownGit, [publish](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) it from your GitHub account, & use from there. ([SO answer](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo/38879691#38879691))

**Comment by Jared-Harrington-Gibbs** [comment]
Yeah, Just had this issue when looking at a [blog template](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/yizeng/jekyll-theme-simple-texture/tree/master/starter-kit).
After looking into it a bit more I'm a solid 70% sure it got flagged for it's relation to your [TrojanCocroach project](https://github.com/MinhasKamal/TrojanCockroach) or [this Minecraft project](https://github.com/tryashtar/datapacks).

Relevant VTGraph [here](https://www.virustotal.com/graph/embed/gb17f31557aa549ac9c9cbb330ebadd88d3e1a49fa8884951b94d1b87e0589acb)

**Comment by MinhasKamal** [comment]
Yes, I assume that too. And I am really sorry for this.

Recently Gowngit has been moved and published from a new place- https://downgit.github.io

**Comment by ComputeShader** [comment]
You can still go on the page by accepting the risk..

**Comment by MinhasKamal** [comment]
Finally, it seems [DownGit](https://minhaskamal.github.io/DownGit) has been exculpated!

**Comment by Xevion** [comment]
![image](https://github.com/user-attachments/assets/7341e6ef-4a87-4452-aea6-8b0dc9937183)


> Finally, it seems [DownGit](https://minhaskamal.github.io/DownGit) has been exculpated!
