### ISSUE TITLE
Favicon Dark mode request

### ISSUE THREAD

**Issue by saravanabalagi** [MinhasKamal/DownGit#33]
The favicon is almost invisible in dark backgrounds.

![image](https://user-images.githubusercontent.com/8567893/88912804-be01d400-d257-11ea-86b1-2af2b913c17a.png)
![image](https://user-images.githubusercontent.com/8567893/88912652-7c712900-d257-11ea-9b04-29284e432774.png)

I suggest having an icon similar to that of Github to make it visible in dark backgrounds?

**Comment by MinhasKamal** [comment]
@saravanabalagi Thanks for pointing it out. May be adding a white border will resolve this.

**Comment by Parsa2820** [comment]
Can I fix this issu?

**Comment by MinhasKamal** [comment]
@Parsa2820 Thank you so much for your kind contribution to the project. 

PS: Really sorry for the late response.
