### ISSUE TITLE
Website marked as dangerous

### ISSUE THREAD

**Issue by ZurMaD** [MinhasKamal/DownGit#36]
I don't know why but this appears each time that I use the webpage

![image](https://user-images.githubusercontent.com/28235457/102120321-6207a880-3e10-11eb-9ee9-ce75494f4ae6.png)

website: https://minhaskamal.github.io/DownGit/#/home

**Comment by MinhasKamal** [comment]
Seems Google falsely marked DownGit as harmful again #31 
@ZurMaD Thanks for reporting this issue. Please use the mirror site for now- https://downgit.github.io

**Comment by franktko** [comment]
BTW, this is still happening. The link on the main DownGit page has this problem. Anyway, thanks for the mirror site!

**Comment by yogiHalim** [comment]
using this https://minhaskamal.github.io/DownGit/#/home
and windows defender found a trojan
