### ISSUE TITLE
Download without folder inside archive

### ISSUE THREAD

**Issue by jan-gerard** [MinhasKamal/DownGit#4]
Hi,
Is there a way to create a zip archive that does not contain a subfolder, but only the contents of that folder directly at the root level of the archive? And is there a way to give the archive a specific name? 
I have a github repository with a directory https://github.com/jan-gerard/EV3_GyroBlox/zipball/master/unzipped, and I would like to create a link that downloads the contents of that folder as a zip file without a sub-folder, with a specific name (EV3_GyroBlox.ev3s) and extension, which is not zip.

**Comment by MinhasKamal** [comment]
1. "Is there a way to create a zip archive that does not contain a subfolder, but only the contents of that folder directly at the root level of the archive?", no, this feature is not added in the application. But it is possible to do that.
2. "Is there a way to give the archive a specific name?", this functionality is not available for now, may be added in future.

**Comment by jan-gerard** [comment]
Hi,

It would be even nicer when it could work vice versa: that you can 
upload a zip-file with a specific extension (mindstormsprogram.ev3s) 
that is unzipped to a specified folder, into its contents, and 
downloaded again as a single zipped file (with extension .ev3s) with the 
contents of this folder.

Best regards,
Jan-Gerard

**Comment by tryashtar** [comment]
Any chance of this getting added? I have a repository set up in such a way that many of the folders are useful to another program when simply zipped up, so I can push changes and provide a simple link to snag the most up-to-date version.

This website was an absolute lifesaver until I noticed it put the folder inside the zip instead of just the contents directly. Now I'm really struggling to find an adequate replacement -- I'd be very grateful if you could implement or change this. Thanks for your work!

**Comment by MinhasKamal** [comment]
Features implemented-
- [x] Contents are added directly into archive, no root folder
- [x] Give the archive a specific name

A link looks like this in general-
`https://thedeepthinker.github.io/DownGit/#/home?url=<link>`

Now, you can pass two new variables-
`https://thedeepthinker.github.io/DownGit/#/home?url=<link>&fileName=<name>&rootDirectory=<true or false or name>`

Download with zip file name- 'octocat', and no root folder-
`https://thedeepthinker.github.io/DownGit/#/home?url=https://github.com/TheDeepThinker/DownGit/tree/master/res/images&fileName=octocat&rootDirectory=false`

You can also give name to the root folder, just pass value except- 'true' or 'false'.

@jan-gerard @tryashtar thank you for your suggestion.

**Comment by tryashtar** [comment]
Thank you so much, I really appreciate it!
