### ISSUE TITLE
 viewport for mobile

### ISSUE THREAD

**Issue by MininxD** [MinhasKamal/DownGit#44]
I need to zoom in when open with mobile
Try add this tag inside head tag

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by MinhasKamal** [comment]
Thanks for the suggestion. I will look into it :)

**Comment by MininxD** [comment]
Hey look this :)

![Screenshot_20211220-144201~3](https://user-images.githubusercontent.com/70429604/146730478-cef8c5a9-bafa-4af3-8b94-1b32ebace76c.jpg)
