### ISSUE TITLE
Using the download link with curl

### ISSUE THREAD

**Issue by pradermecker** [MinhasKamal/DownGit#6]
Is it possible to use the download link in a shell ? Something alike : 
```
curl -L https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/CIRB/devbox/tree/v3/user/config
```

Thanks for building this handy tool.

**Comment by MinhasKamal** [comment]
Thanks a lot for your response :smile: 

The entire process is performed on the client side (browser) using JavaScript. So, the command should not work. But you may directly download the folder from GitHub by command (without using DownGit).

**Comment by manueldeprada** [comment]
Just wanted to add here, it would be really cool if this was also a command line helper. thx for the tool!
