### ISSUE TITLE
Damaged archive

### ISSUE THREAD

**Issue by ukod** [MinhasKamal/DownGit#8]
When I had downloaded folder by this link https://github.com/xamarin/ios-samples/tree/master/WatchKit/WatchKitCatalog output archive is damaged.

**Comment by MinhasKamal** [comment]
I have successfully downloaded the directory ([here](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/xamarin/ios-samples/tree/master/WatchKit/WatchKitCatalog)), & could not spot any problem.

You may try to re-download it. Please notify if you face the same problem again.

Thank you :)

**Comment by ukod** [comment]
I tried it several times. This thing is strange because other repos downloaded successfully. Maybe it's my local problem, but I'm not sure.

**Comment by MinhasKamal** [comment]
I have tried your link again with both Google Chrome and Mizilla Firefox; the download was successful. So, may be it is a local problem.
