### ISSUE TITLE
Downloaded Directory do not contain file inside the sub-folder

### ISSUE THREAD

**Issue by shingz96** [MinhasKamal/DownGit#9]
try with this link: https://github.com/iluwatar/java-design-patterns/tree/master/flyweight

inside the `src/main/java/com/iluwatar/flyweight` suppose to have files like java codes, but only sub-folders are download and archived.

**Comment by MinhasKamal** [comment]
Experiencing the same here too. Strangely DownGit is not working on this link straight too- https://github.com/iluwatar/java-design-patterns/tree/master/flyweight/src/main/java/com/iluwatar/flyweight. 

Thanks a lot for your help. I will take a look and let you know. :)

**Comment by MinhasKamal** [comment]
In the directory path- https://github.com/iluwatar/java-design-patterns/tree/master/flyweight there is folder named "flyweight". For getting the same name as root directory, my code was failing. I have solved the bug. The patch will go live soon.

@shingz96 thank you a lot for filing the issue.
